# Generated by Django 5.2 on 2025-05-21 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_review_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review_per_user',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user',)},
        ),
    ]
