# Generated by Django 5.2 on 2025-08-22 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beverage',
            options={},
        ),
    ]
