# Generated by Django 5.2 on 2025-11-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gcash_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='gcash_receipts/'),
        ),
    ]
