# Generated by Django 5.2 on 2025-11-16 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_order_gcash_receipt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderStatus',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantity',
            new_name='cases_ordered',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='cases_ordered',
        ),
    ]
