# Generated by Django 5.2 on 2025-11-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_delete_orderstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='stock',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='cases_ordered',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10),
        ),
    ]
