# Generated by Django 5.2 on 2025-11-16 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
