# Generated by Django 5.2 on 2025-12-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_order_latitude_order_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
