# Generated by Django 5.2 on 2025-12-12 22:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_beverage_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='barangay',
            field=models.CharField(blank=True, choices=[('Dalahican', 'Dalahican'), ('Cotta', 'Cotta'), ('Dupay', 'Dupay'), ('Iyam', 'Iyam'), ('Market View', 'Market View'), ('Mayao', 'Mayao'), ('Talao-talao', 'Talao-talao')], help_text='Barangay for delivery location', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
