# Generated by Django 5.2 on 2025-12-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_order_barangay_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='allow_half_case',
            field=models.BooleanField(default=True),
        ),
    ]
