# Generated by Django 5.1.6 on 2026-01-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_beverage_allow_half_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='unit_label',
            field=models.CharField(default='case', max_length=20),
        ),
    ]
