# Generated by Django 5.1.6 on 2026-01-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_beverage_unit_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='unit_label',
            field=models.CharField(choices=[('case', 'Case'), ('box', 'Box'), ('pack', 'Pack'), ('carton', 'Carton')], default='case', max_length=20),
        ),
    ]
