# Generated by Django 5.2 on 2026-01-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_beverage_unit_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='barangay',
            field=models.CharField(blank=True, choices=[('Barangay 1', 'Barangay 1'), ('Barangay 2', 'Barangay 2'), ('Barangay 3', 'Barangay 3'), ('Barangay 4', 'Barangay 4'), ('Barangay 5', 'Barangay 5'), ('Barangay 6', 'Barangay 6'), ('Barangay 7', 'Barangay 7'), ('Barangay 8', 'Barangay 8'), ('Barangay 9', 'Barangay 9'), ('Barangay 10', 'Barangay 10'), ('Barangay 11', 'Barangay 11'), ('Barra', 'Barra'), ('Bocohan', 'Bocohan'), ('Cotta', 'Cotta'), ('Dalahican', 'Dalahican'), ('Domot', 'Domot'), ('Gulang-gulang', 'Gulang-gulang'), ('Ibabang Dupay', 'Ibabang Dupay'), ('Ibabang Iyam', 'Ibabang Iyam'), ('Ilayang Dupay', 'Ilayang Dupay'), ('Ilayang Iyam', 'Ilayang Iyam'), ('Iyam', 'Iyam'), ('Isabang', 'Isabang'), ('Market View', 'Market View'), ('Mayao Castillo', 'Mayao Castillo'), ('Mayao Crossing', 'Mayao Crossing'), ('Mayao Kanluran', 'Mayao Kanluran'), ('Mayao Parada', 'Mayao Parada'), ('Mayao Silangan', 'Mayao Silangan'), ('Ransohan', 'Ransohan'), ('Salinas', 'Salinas'), ('Talao-talao', 'Talao-talao')], help_text='Barangay for delivery location', max_length=100, null=True),
        ),
    ]
