# Generated by Django 5.2 on 2026-01-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_alter_order_barangay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='barangay',
            field=models.CharField(blank=True, choices=[('Alitap', 'Alitap'), ('Bacag', 'Bacag'), ('Bagong Silang', 'Bagong Silang'), ('Barayong', 'Barayong'), ('Barra', 'Barra'), ('Bocohan', 'Bocohan'), ('Bungoy', 'Bungoy'), ('Cotta', 'Cotta'), ('Dalahican', 'Dalahican'), ('Dapdap', 'Dapdap'), ('Del Rosario', 'Del Rosario'), ('Dolores', 'Dolores'), ('Domot', 'Domot'), ('Dupay', 'Dupay'), ('Gulang-gulang', 'Gulang-gulang'), ('Ibabang Dupay', 'Ibabang Dupay'), ('Ibabang Iyam', 'Ibabang Iyam'), ('Ibabang Talim', 'Ibabang Talim'), ('Ilayang Dupay', 'Ilayang Dupay'), ('Ilayang Iyam', 'Ilayang Iyam'), ('Ilayang Talim', 'Ilayang Talim'), ('Isabang', 'Isabang'), ('Iyam', 'Iyam'), ('Kambal Na Pulo', 'Kambal Na Pulo'), ('Lalaguna', 'Lalaguna'), ('Maligaya', 'Maligaya'), ('Market View', 'Market View'), ('Mayao Castillo', 'Mayao Castillo'), ('Mayao Crossing', 'Mayao Crossing'), ('Mayao Kanluran', 'Mayao Kanluran'), ('Mayao Parada', 'Mayao Parada'), ('Mayao Silangan', 'Mayao Silangan'), ('Medina', 'Medina'), ('Pagsawitan', 'Pagsawitan'), ('Panayonan', 'Panayonan'), ('Pantay Kanluran', 'Pantay Kanluran'), ('Pantay Silangan', 'Pantay Silangan'), ('Poblacion', 'Poblacion'), ('Ransohan', 'Ransohan'), ('Salinas', 'Salinas'), ('Sanggalang', 'Sanggalang'), ('Talao-talao', 'Talao-talao'), ('Tayabas Bay', 'Tayabas Bay'), ('Tayuman', 'Tayuman'), ('Urdaneta', 'Urdaneta')], help_text='Barangay for delivery location', max_length=100, null=True),
        ),
    ]
