# Generated by Django 5.2 on 2026-01-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_order_barangay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('In Transit', 'In Transit'), ('Delivered by Staff', 'Delivered by Staff'), ('Confirmed by Customer', 'Confirmed by Customer'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=25),
        ),
    ]
