# Generated by Django 5.2 on 2026-01-19 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Barangay',
                'verbose_name_plural': 'Barangays',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiar_barangays', models.ManyToManyField(blank=True, help_text='Barangays this staff is familiar with', to='api.barangay')),
                ('preferred_vehicle', models.ForeignKey(blank=True, help_text='Default vehicle this staff uses', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vehicle')),
                ('staff', models.OneToOneField(limit_choices_to={'role': 'staff'}, on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
