# Generated by Django 5.2 on 2026-01-19 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_barangay_staffpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffpreference',
            name='familiar_barangays',
        ),
        migrations.RemoveField(
            model_name='staffpreference',
            name='preferred_vehicle',
        ),
        migrations.RemoveField(
            model_name='staffpreference',
            name='staff',
        ),
        migrations.AddField(
            model_name='customuser',
            name='familiar_barangays',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_staff', to='api.vehicle'),
        ),
        migrations.DeleteModel(
            name='Barangay',
        ),
        migrations.DeleteModel(
            name='StaffPreference',
        ),
    ]
