# Generated by Django 5.2 on 2026-01-21 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_remove_staffpreference_familiar_barangays_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiar_barangays', models.JSONField(blank=True, default=list)),
                ('preferred_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vehicle')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
